<?php
/**
 * @var \Pimcore\Bundle\PimcoreBundle\Templating\PhpEngine $this
 * @var \Pimcore\Bundle\PimcoreBundle\Templating\PhpEngine $view
 * @var \Pimcore\Bundle\PimcoreBundle\Templating\GlobalVariables\GlobalVariables $app
 */
?>


<?php
    // add autogenerated meta description
    $this->headMeta()->setDescription($this->wysiwyg("content")->getData(), 160);
?>

<section class="area-wysiwyg">

    <div class="row">
        <div class="col-sm-8">
            <?php $this->glossary()->start(); ?>
                <?= $this->wysiwyg("content"); ?>
            <?php $this->glossary()->stop(); ?>
        </div>
        <div class="col-sm-4">
            <?php while ($this->block("images")->loop()) { ?>
                <?php if(!$this->editmode) { ?>
                    <a href="<?= $this->image("image")->getThumbnail("galleryLightbox"); ?>" class="thumbnail">
                <?php } ?>

                    <?= $this->image("image", [
                        "thumbnail" => "galleryThumbnail"
                    ]); ?>

                <?php if(!$this->editmode) { ?>
                    </a>
                <?php } ?>
            <?php } ?>
        </div>
    </div>
</section>
