monolog:
    handlers:
        main:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%-error.log"
            level: error
        console:
            type: console
            process_psr_3_messages: false
