<?php
declare(strict_types=1);

/**
 * This source file is available under the terms of the
 * Pimcore Open Core License (POCL)
 * Full copyright and license information is available in
 * LICENSE.md which is distributed with this source code.
 *
 *  @copyright  Copyright (c) Pimcore GmbH (https://www.pimcore.com)
 *  @license    Pimcore Open Core License (POCL)
 */

namespace Pimcore\Tests\Unit\InstallBundle\EnvVarDefinition\Definitions;

use Defuse\Crypto\Key;
use Pimcore\Bundle\InstallBundle\EnvVarDefinition\Definitions\ProductRegistrationEnvVarDefinition;
use Pimcore\Bundle\InstallBundle\EnvVarDefinition\ParameterHintProviderInterface;
use Pimcore\Tests\Support\Test\TestCase;

/**
 * @internal
 */
final class ProductRegistrationEnvVarDefinitionTest extends TestCase
{
    private ProductRegistrationEnvVarDefinition $definition;

    protected function setUp(): void
    {
        parent::setUp();
        $this->definition = new ProductRegistrationEnvVarDefinition();
    }

    public function testMetadata(): void
    {
        $this->assertSame('product-registration', $this->definition->getKey());
        $this->assertSame('Product Registration', $this->definition->getLabel());
        $this->assertTrue($this->definition->isRequired());
        $this->assertSame('pimcore/pimcore', $this->definition->getSectionName());
    }

    public function testParametersContainAllThreeFields(): void
    {
        $params = $this->definition->getParameters();
        $this->assertCount(3, $params);

        $envVarNames = array_map(
            static fn ($p) => $p->getEnvVarName(),
            $params,
        );

        $this->assertContains('PIMCORE_ENCRYPTION_SECRET', $envVarNames);
        $this->assertContains('PIMCORE_INSTANCE_IDENTIFIER', $envVarNames);
        $this->assertContains('PIMCORE_PRODUCT_KEY', $envVarNames);
    }

    public function testEncryptionSecretHasAutoGeneratedDefault(): void
    {
        $params = $this->definition->getParameters();
        $secretParam = $params[0];

        $this->assertSame('PIMCORE_ENCRYPTION_SECRET', $secretParam->getEnvVarName());
        $this->assertNotNull($secretParam->getDefaultValue());
        $this->assertNotSame('', $secretParam->getDefaultValue());

        // Verify it's a valid Defuse key
        $key = Key::loadFromAsciiSafeString($secretParam->getDefaultValue());
        $this->assertInstanceOf(Key::class, $key);
    }

    public function testInstanceIdentifierHasAutoGeneratedDefault(): void
    {
        $params = $this->definition->getParameters();
        $identifierParam = $params[1];

        $this->assertSame('PIMCORE_INSTANCE_IDENTIFIER', $identifierParam->getEnvVarName());
        $this->assertNotNull($identifierParam->getDefaultValue());
        $this->assertNotSame('', $identifierParam->getDefaultValue());
    }

    public function testResolveEnvVars(): void
    {
        $envVars = $this->definition->resolveEnvVars([
            'PIMCORE_ENCRYPTION_SECRET' => 'test-secret',
            'PIMCORE_INSTANCE_IDENTIFIER' => 'test-id',
            'PIMCORE_PRODUCT_KEY' => 'test-key',
        ]);

        $this->assertSame('test-secret', $envVars['PIMCORE_ENCRYPTION_SECRET']);
        $this->assertSame('test-id', $envVars['PIMCORE_INSTANCE_IDENTIFIER']);
        $this->assertSame('test-key', $envVars['PIMCORE_PRODUCT_KEY']);
    }

    public function testResolveEnvVarsWithDefaults(): void
    {
        $envVars = $this->definition->resolveEnvVars([]);

        $this->assertSame('', $envVars['PIMCORE_ENCRYPTION_SECRET']);
        $this->assertSame('', $envVars['PIMCORE_INSTANCE_IDENTIFIER']);
        $this->assertSame('', $envVars['PIMCORE_PRODUCT_KEY']);
    }

    public function testValidateRejectsEmptySecret(): void
    {
        $errors = $this->definition->validate([
            'PIMCORE_ENCRYPTION_SECRET' => '',
            'PIMCORE_INSTANCE_IDENTIFIER' => 'test-id',
            'PIMCORE_PRODUCT_KEY' => 'test-key',
        ]);

        $this->assertNotEmpty($errors);
        $this->assertStringContainsString('Encryption secret', $errors[0]);
    }

    public function testValidateRejectsEmptyInstanceIdentifier(): void
    {
        $errors = $this->definition->validate([
            'PIMCORE_ENCRYPTION_SECRET' => 'some-secret',
            'PIMCORE_INSTANCE_IDENTIFIER' => '',
            'PIMCORE_PRODUCT_KEY' => 'test-key',
        ]);

        $this->assertNotEmpty($errors);
        $this->assertStringContainsString('Instance identifier', $errors[0]);
    }

    public function testValidateRejectsEmptyProductKey(): void
    {
        $errors = $this->definition->validate([
            'PIMCORE_ENCRYPTION_SECRET' => 'some-secret',
            'PIMCORE_INSTANCE_IDENTIFIER' => 'test-id',
            'PIMCORE_PRODUCT_KEY' => '',
        ]);

        $this->assertNotEmpty($errors);
        $this->assertStringContainsString('Product key', $errors[0]);
    }

    public function testValidateRejectsInvalidDefuseKey(): void
    {
        $errors = $this->definition->validate([
            'PIMCORE_ENCRYPTION_SECRET' => 'not-a-valid-defuse-key',
            'PIMCORE_INSTANCE_IDENTIFIER' => 'test-id',
            'PIMCORE_PRODUCT_KEY' => 'test-key',
        ]);

        $this->assertNotEmpty($errors);
        $this->assertStringContainsString('Invalid encryption secret', $errors[0]);
        $this->assertStringContainsString('generate-defuse-key', $errors[0]);
    }

    public function testValidateRejectsInvalidProductKey(): void
    {
        // Use a valid Defuse key but an invalid product key
        $secret = Key::createNewRandomKey()->saveToAsciiSafeString();

        $errors = $this->definition->validate([
            'PIMCORE_ENCRYPTION_SECRET' => $secret,
            'PIMCORE_INSTANCE_IDENTIFIER' => 'test-instance-id',
            'PIMCORE_PRODUCT_KEY' => 'invalid-product-key',
        ]);

        $this->assertNotEmpty($errors);
        // RegistrationValidator throws InvalidConfigurationException for invalid keys
        $this->assertStringContainsString('product key', strtolower($errors[0]));
    }

    public function testGetParametersReturnsStableDefaultsAcrossCalls(): void
    {
        $firstCallParams = $this->definition->getParameters();
        $secondCallParams = $this->definition->getParameters();

        // The auto-generated defaults should be identical across calls (I17 fix)
        $this->assertSame(
            $firstCallParams[0]->getDefaultValue(),
            $secondCallParams[0]->getDefaultValue(),
            'PIMCORE_ENCRYPTION_SECRET default should be stable across calls',
        );
        $this->assertSame(
            $firstCallParams[1]->getDefaultValue(),
            $secondCallParams[1]->getDefaultValue(),
            'PIMCORE_INSTANCE_IDENTIFIER default should be stable across calls',
        );
    }

    public function testImplementsParameterHintProviderInterface(): void
    {
        $this->assertInstanceOf(ParameterHintProviderInterface::class, $this->definition);
    }

    public function testGetParameterHintReturnsNullForNonProductKey(): void
    {
        $hint = $this->definition->getParameterHint('PIMCORE_ENCRYPTION_SECRET', []);
        $this->assertNull($hint);

        $hint = $this->definition->getParameterHint('PIMCORE_INSTANCE_IDENTIFIER', [
            'PIMCORE_ENCRYPTION_SECRET' => 'some-secret',
        ]);
        $this->assertNull($hint);
    }

    public function testGetParameterHintReturnsRegistrationLinkForProductKey(): void
    {
        $secret = Key::createNewRandomKey()->saveToAsciiSafeString();
        $instanceId = 'test-instance-123';

        $hint = $this->definition->getParameterHint('PIMCORE_PRODUCT_KEY', [
            'PIMCORE_ENCRYPTION_SECRET' => $secret,
            'PIMCORE_INSTANCE_IDENTIFIER' => $instanceId,
        ]);

        $this->assertNotNull($hint);
        $this->assertStringContainsString('https://license.pimcore.com/register', $hint);
        $this->assertStringContainsString('instance_identifier=' . $instanceId, $hint);
        $this->assertStringContainsString('instance_hash=', $hint);
    }

    public function testGetParameterHintReturnsNullWhenSecretMissing(): void
    {
        $hint = $this->definition->getParameterHint('PIMCORE_PRODUCT_KEY', [
            'PIMCORE_INSTANCE_IDENTIFIER' => 'test-id',
        ]);

        $this->assertNull($hint);
    }

    public function testGetParameterHintReturnsNullWhenSecretInvalid(): void
    {
        $hint = $this->definition->getParameterHint('PIMCORE_PRODUCT_KEY', [
            'PIMCORE_ENCRYPTION_SECRET' => 'not-a-valid-key',
            'PIMCORE_INSTANCE_IDENTIFIER' => 'test-id',
        ]);

        $this->assertNull($hint);
    }

    public function testGetParameterHintReturnsNullWhenIdentifierMissing(): void
    {
        $secret = Key::createNewRandomKey()->saveToAsciiSafeString();

        $hint = $this->definition->getParameterHint('PIMCORE_PRODUCT_KEY', [
            'PIMCORE_ENCRYPTION_SECRET' => $secret,
        ]);

        $this->assertNull($hint);
    }
}
