daysUntilStale: 7
daysUntilClose: 180
exemptLabels:
    - Priority
    - Critical
staleLabel: "PR Welcome"
markComment: >
    Thanks a lot for reporting the issue.
    The issue was not considered by us as "critical" or "priority",
    so we're not gonna work on that anytime soon.
    In case this is a bug report, please create a pull request fixing the issue,
    we'll then review it as soon as possible.
    If you're interested in contributing a feature, please contact us first here
    before creating a pull request, we'll then decide whether we'd accept it or not.
    Thanks for your understanding.
closeComment: >
    Closed due to inactivity (180 days).
    Please feel free to continue the discussion or provide the missing information on this issue,
    we'll then reopen it if necessary.
    Thanks a lot!