services:
    _defaults:
        autowire: true
        autoconfigure: true

    #
    # INSTALLER
    #

    Pimcore\Bundle\SeoBundle\Installer:
        public: true
        arguments:
            $bundle: "@=service('kernel').getBundle('PimcoreSeoBundle')"
