framework:
    messenger:
        transports:
            pimcore_search_backend_message: "%pimcore.messenger.transport_dsn%?queue_name=pimcore_search_backend_message"
        routing:
            Pimcore\Bundle\SimpleBackendSearchBundle\Message\SearchBackendMessage: pimcore_search_backend_message
