<?php

return [
//            '/bundles/pimcoreadmin/js/pimcore/common.js',
    '/bundles/pimcoreadmin/js/lib/class.js',
    '/bundles/pimcoreadmin/js/lib/ckeditor/ckeditor.js',
    '/bundles/pimcoreadmin/js/pimcore/functions.js',
    '/bundles/pimcoreadmin/js/pimcore/overrides.js',
    '/bundles/pimcoreadmin/js/pimcore/tool/milestoneslider.js',
    '/bundles/pimcoreadmin/js/pimcore/element/tag/imagehotspotmarkereditor.js',
    '/bundles/pimcoreadmin/js/pimcore/element/tag/imagecropper.js',
    '/bundles/pimcoreadmin/js/pimcore/document/edit/helper.js',
    '/bundles/pimcoreadmin/js/pimcore/elementservice.js',
    '/bundles/pimcoreadmin/js/pimcore/document/edit/dnd.js',
    '/bundles/pimcoreadmin/js/pimcore/document/editable.js',
    '/bundles/pimcoreadmin/js/pimcore/document/editables/block.js',
    '/bundles/pimcoreadmin/js/pimcore/document/editables/scheduledblock.js',
    '/bundles/pimcoreadmin/js/pimcore/document/editables/date.js',
    '/bundles/pimcoreadmin/js/pimcore/document/editables/relation.js',
    '/bundles/pimcoreadmin/js/pimcore/document/editables/relations.js',
    '/bundles/pimcoreadmin/js/pimcore/document/editables/checkbox.js',
    '/bundles/pimcoreadmin/js/pimcore/document/editables/image.js',
    '/bundles/pimcoreadmin/js/pimcore/document/editables/input.js',
    '/bundles/pimcoreadmin/js/pimcore/document/editables/link.js',
    '/bundles/pimcoreadmin/js/pimcore/document/editables/select.js',
    '/bundles/pimcoreadmin/js/pimcore/document/editables/snippet.js',
    '/bundles/pimcoreadmin/js/pimcore/document/editables/textarea.js',
    '/bundles/pimcoreadmin/js/pimcore/document/editables/numeric.js',
    '/bundles/pimcoreadmin/js/pimcore/document/editables/wysiwyg.js',
    '/bundles/pimcoreadmin/js/pimcore/document/editables/renderlet.js',
    '/bundles/pimcoreadmin/js/pimcore/document/editables/table.js',
    '/bundles/pimcoreadmin/js/pimcore/document/editables/video.js',
    '/bundles/pimcoreadmin/js/pimcore/document/editables/multiselect.js',
    '/bundles/pimcoreadmin/js/pimcore/document/editables/areablock.js',
    '/bundles/pimcoreadmin/js/pimcore/document/editables/area.js',
    '/bundles/pimcoreadmin/js/pimcore/document/editables/pdf.js',
    '/bundles/pimcoreadmin/js/pimcore/document/editables/embed.js',
    '/bundles/pimcoreadmin/js/pimcore/document/edit/helper.js',

    '/bundles/pimcoreadmin/js/pimcore/document/edit/startup.js',
];
