<?php  //[STAMP] 5348900afb80643b28677e69ac0ba8ba

namespace EcommerceFramework\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

use EcommerceFramework\Helper\Functional;

trait FunctionalTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();
}
