<?php

declare(strict_types=1);

/**
 * This source file is available under the terms of the
 * Pimcore Open Core License (POCL)
 * Full copyright and license information is available in
 * LICENSE.md which is distributed with this source code.
 *
 *  @copyright  Copyright (c) Pimcore GmbH (https://www.pimcore.com)
 *  @license    Pimcore Open Core License (POCL)
 */

namespace Pimcore\Tests\Unit\Models\Asset\Image\Thumbnail;

use Pimcore\Model\Asset\Image\Thumbnail\Config;
use Pimcore\Tests\Support\Test\TestCase;

/**
 * Regression tests for Config::getHash().
 *
 * The crop box flag was introduced into the hash in 12.3.0 (#18317). Adding it
 * unconditionally changed the filename hash of EVERY thumbnail on upgrade -
 * including the vast majority that never use the crop box - forcing a full,
 * unnecessary regeneration and leaving orphaned files on storage. The hash must
 * therefore remain backward compatible whenever the crop box is not enabled.
 *
 * NOTE: Config is a final class and cannot be mocked. Real Config objects are
 * constructed via setters instead.
 */
class ConfigHashTest extends TestCase
{
    private function config(bool $useCropBox = false): Config
    {
        $config = new Config();
        $config->setItems([
            ['method' => 'resize', 'arguments' => ['width' => 400, 'height' => 300]],
        ]);
        $config->setUseCropBox($useCropBox);

        return $config;
    }

    /**
     * With the crop box disabled (the default), the hash must match the
     * pre-12.3.0 serialization layout, which did not contain the crop box flag
     * at all. This is the property that prevents a forced full regeneration on
     * upgrade.
     */
    public function testCropBoxDisabledKeepsLegacyHash(): void
    {
        $config = $this->config(false);

        $legacyHash = hash('xxh32', serialize([
            $config->getPreserveAnimation(),
            $config->getQuality(),
            $config->isPreserveColor(),
            $config->isPreserveMetaData(),
            $config->getItems(),
            [],
        ]));

        $this->assertSame($legacyHash, $config->getHash());
    }

    /**
     * Enabling the crop box must change the hash so that crop-box thumbnails do
     * not collide with regular ones, and must match the layout that appends the
     * flag before the items (identical to the 12.3.x serialization).
     */
    public function testCropBoxEnabledAppendsFlagToHash(): void
    {
        $config = $this->config(true);

        $enabledHash = hash('xxh32', serialize([
            $config->getPreserveAnimation(),
            $config->getQuality(),
            $config->isPreserveColor(),
            $config->isPreserveMetaData(),
            true,
            $config->getItems(),
            [],
        ]));

        $this->assertSame($enabledHash, $config->getHash());
    }

    /**
     * Toggling the crop box must produce two distinct hashes for otherwise
     * identical configs.
     */
    public function testCropBoxToggleProducesDistinctHashes(): void
    {
        $this->assertNotSame(
            $this->config(false)->getHash(),
            $this->config(true)->getHash(),
        );
    }

    /**
     * The compat hash reproduces the Pimcore 12.3.0-12.3.11 layout, in which the
     * crop box flag was always serialized. For a disabled config this differs
     * from getHash() and is what the Processor lookup falls back to so thumbnails
     * generated by those versions are reused rather than regenerated.
     */
    public function testCropBoxCompatHashReproducesLegacy123Layout(): void
    {
        $config = $this->config(false);

        $compatHash = hash('xxh32', serialize([
            $config->getPreserveAnimation(),
            $config->getQuality(),
            $config->isPreserveColor(),
            $config->isPreserveMetaData(),
            false,
            $config->getItems(),
            [],
        ]));

        $this->assertSame($compatHash, $config->getCropBoxCompatHash());
        $this->assertNotSame($config->getHash(), $config->getCropBoxCompatHash());
    }

    /**
     * When the crop box is enabled, getHash() already includes the flag, so the
     * compat hash must be identical - no fallback lookup is needed in that case.
     */
    public function testCropBoxCompatHashEqualsHashWhenEnabled(): void
    {
        $config = $this->config(true);

        $this->assertSame($config->getHash(), $config->getCropBoxCompatHash());
    }

    /**
     * The extra $params argument must continue to participate in the hash in
     * both crop box states.
     */
    public function testParamsStillAffectHash(): void
    {
        foreach ([false, true] as $useCropBox) {
            $config = $this->config($useCropBox);
            $this->assertNotSame(
                $config->getHash(),
                $config->getHash(['foo' => 'bar']),
                'params must affect the hash (useCropBox=' . var_export($useCropBox, true) . ')',
            );
        }
    }
}
