services:
    _defaults:
        autowire: true
        autoconfigure: true

    Pimcore\Bundle\InstallBundle\Command\InstallCommand:
        public: true
        tags: ['console.command']
        arguments:
            $secret: '%secret%'

    Pimcore\Composer\PackageInfo: ~

    Pimcore\Bundle\InstallBundle\Installer: ~