<?php

// get db connection
$db = Pimcore_Resource_Mysql::get("database");

$db->getConnection()->exec("ALTER TABLE `assets` CHANGE COLUMN `id` `id` int(11) unsigned NOT NULL AUTO_INCREMENT;");
$db->getConnection()->exec("ALTER TABLE `assets` CHANGE COLUMN `parentId` `parentId` int(11) unsigned NULL DEFAULT NULL;");
$db->getConnection()->exec("ALTER TABLE `assets` CHANGE COLUMN `creationDate` `creationDate` bigint(20) unsigned NULL DEFAULT NULL;");
$db->getConnection()->exec("ALTER TABLE `assets` CHANGE COLUMN `modificationDate` `modificationDate` bigint(20) unsigned NULL DEFAULT NULL;");
$db->getConnection()->exec("ALTER TABLE `assets` CHANGE COLUMN `userOwner` `userOwner` int(11) unsigned NULL DEFAULT NULL;");
$db->getConnection()->exec("ALTER TABLE `assets` CHANGE COLUMN `userModification` `userModification` int(11) unsigned NULL DEFAULT NULL;");
$db->getConnection()->exec("ALTER TABLE `assets_permissions` CHANGE COLUMN `id` `id` int(11) unsigned NOT NULL AUTO_INCREMENT;");
$db->getConnection()->exec("ALTER TABLE `assets_permissions` CHANGE COLUMN `cid` `cid` int(11) unsigned NULL DEFAULT NULL;");
$db->getConnection()->exec("ALTER TABLE `assets_permissions` CHANGE COLUMN `userId` `userId` int(11) unsigned NULL DEFAULT NULL;");
$db->getConnection()->exec("ALTER TABLE `assets_permissions` CHANGE COLUMN `list` `list` tinyint(1) NULL DEFAULT 0;");
$db->getConnection()->exec("ALTER TABLE `assets_permissions` CHANGE COLUMN `view` `view` tinyint(1) NULL DEFAULT 0;");
$db->getConnection()->exec("ALTER TABLE `assets_permissions` CHANGE COLUMN `publish` `publish` tinyint(1) NULL DEFAULT 0;");
$db->getConnection()->exec("ALTER TABLE `assets_permissions` CHANGE COLUMN `delete` `delete` tinyint(1) NULL DEFAULT 0;");
$db->getConnection()->exec("ALTER TABLE `assets_permissions` CHANGE COLUMN `rename` `rename` tinyint(1) NULL DEFAULT 0;");
$db->getConnection()->exec("ALTER TABLE `assets_permissions` CHANGE COLUMN `create` `create` tinyint(1) NULL DEFAULT 0;");
$db->getConnection()->exec("ALTER TABLE `assets_permissions` CHANGE COLUMN `permissions` `permissions` tinyint(1) NULL DEFAULT 0;");
$db->getConnection()->exec("ALTER TABLE `assets_permissions` CHANGE COLUMN `settings` `settings` tinyint(1) NULL DEFAULT 0;");
$db->getConnection()->exec("ALTER TABLE `assets_permissions` CHANGE COLUMN `versions` `versions` tinyint(1) NULL DEFAULT 0;");
$db->getConnection()->exec("ALTER TABLE `assets_permissions` CHANGE COLUMN `properties` `properties` tinyint(1) NULL DEFAULT 0;");
$db->getConnection()->exec("ALTER TABLE `classes` CHANGE COLUMN `id` `id` int(11) unsigned NOT NULL AUTO_INCREMENT;");
$db->getConnection()->exec("ALTER TABLE `classes` CHANGE COLUMN `creationDate` `creationDate` bigint(20) unsigned NULL DEFAULT NULL;");
$db->getConnection()->exec("ALTER TABLE `classes` CHANGE COLUMN `modificationDate` `modificationDate` bigint(20) unsigned NULL DEFAULT NULL;");
$db->getConnection()->exec("ALTER TABLE `classes` CHANGE COLUMN `userOwner` `userOwner` int(11) unsigned NULL DEFAULT NULL;");
$db->getConnection()->exec("ALTER TABLE `classes` CHANGE COLUMN `userModification` `userModification` int(11) unsigned NULL DEFAULT NULL;");
$db->getConnection()->exec("ALTER TABLE `classes` CHANGE COLUMN `allowInherit` `allowInherit` tinyint(1) unsigned NULL DEFAULT 0;");
$db->getConnection()->exec("ALTER TABLE `dependencies` CHANGE COLUMN `sourceid` `sourceid` int(11) unsigned NOT NULL DEFAULT 0;");
$db->getConnection()->exec("ALTER TABLE `dependencies` CHANGE COLUMN `targetid` `targetid` int(11) unsigned NOT NULL DEFAULT 0;");
$db->getConnection()->exec("ALTER TABLE `dependencies` ADD INDEX `sourceid` (`sourceid`);");
$db->getConnection()->exec("ALTER TABLE `dependencies` ADD INDEX `targetid` (`targetid`);");
$db->getConnection()->exec("ALTER TABLE `documents` CHANGE COLUMN `id` `id` int(11) unsigned NOT NULL AUTO_INCREMENT;");
$db->getConnection()->exec("ALTER TABLE `documents` CHANGE COLUMN `parentId` `parentId` int(11) unsigned NULL DEFAULT NULL;");
$db->getConnection()->exec("ALTER TABLE `documents` CHANGE COLUMN `index` `index` int(11) unsigned NULL DEFAULT 999999;");
$db->getConnection()->exec("ALTER TABLE `documents` CHANGE COLUMN `published` `published` tinyint(1) unsigned NULL DEFAULT 1;");
$db->getConnection()->exec("ALTER TABLE `documents` CHANGE COLUMN `creationDate` `creationDate` bigint(20) unsigned NULL DEFAULT NULL;");
$db->getConnection()->exec("ALTER TABLE `documents` CHANGE COLUMN `modificationDate` `modificationDate` bigint(20) unsigned NULL DEFAULT NULL;");
$db->getConnection()->exec("ALTER TABLE `documents` CHANGE COLUMN `userOwner` `userOwner` int(11) unsigned NULL DEFAULT NULL;");
$db->getConnection()->exec("ALTER TABLE `documents` CHANGE COLUMN `userModification` `userModification` int(11) unsigned NULL DEFAULT NULL;");
$db->getConnection()->exec("ALTER TABLE `documents_docTypes` CHANGE COLUMN `id` `id` int(11) unsigned NOT NULL AUTO_INCREMENT;");
$db->getConnection()->exec("ALTER TABLE `documents_elements` CHANGE COLUMN `documentId` `documentId` int(11) unsigned NULL DEFAULT NULL;");
$db->getConnection()->exec("ALTER TABLE `documents_link` CHANGE COLUMN `id` `id` int(11) unsigned NULL DEFAULT 0;");
$db->getConnection()->exec("ALTER TABLE `documents_link` CHANGE COLUMN `internal` `internal` int(11) unsigned NULL DEFAULT NULL;");
$db->getConnection()->exec("ALTER TABLE `documents_page` CHANGE COLUMN `id` `id` int(11) unsigned NULL DEFAULT 0;");
$db->getConnection()->exec("ALTER TABLE `documents_permissions` CHANGE COLUMN `id` `id` int(11) unsigned NOT NULL AUTO_INCREMENT");
$db->getConnection()->exec("ALTER TABLE `documents_permissions` CHANGE COLUMN `cid` `cid` int(11) unsigned NULL DEFAULT NULL;");
$db->getConnection()->exec("ALTER TABLE `documents_permissions` CHANGE COLUMN `userId` `userId` int(11) unsigned NULL DEFAULT NULL;");
$db->getConnection()->exec("ALTER TABLE `documents_permissions` CHANGE COLUMN `list` `list` tinyint(1) unsigned NULL DEFAULT 0;");
$db->getConnection()->exec("ALTER TABLE `documents_permissions` CHANGE COLUMN `save` `save` tinyint(1) unsigned NULL DEFAULT 0;");
$db->getConnection()->exec("ALTER TABLE `documents_permissions` CHANGE COLUMN `publish` `publish` tinyint(1) unsigned NULL DEFAULT 0;");
$db->getConnection()->exec("ALTER TABLE `documents_permissions` CHANGE COLUMN `unpublish` `unpublish` tinyint(1) unsigned NULL DEFAULT 0;");
$db->getConnection()->exec("ALTER TABLE `documents_permissions` CHANGE COLUMN `delete` `delete` tinyint(1) unsigned NULL DEFAULT 0;");
$db->getConnection()->exec("ALTER TABLE `documents_permissions` CHANGE COLUMN `rename` `rename` tinyint(1) unsigned NULL DEFAULT 0;");
$db->getConnection()->exec("ALTER TABLE `documents_permissions` CHANGE COLUMN `create` `create` tinyint(1) unsigned NULL DEFAULT 0;");
$db->getConnection()->exec("ALTER TABLE `documents_permissions` CHANGE COLUMN `permissions` `permissions` tinyint(1) unsigned NULL DEFAULT 0;");
$db->getConnection()->exec("ALTER TABLE `documents_permissions` CHANGE COLUMN `settings` `settings` tinyint(1) unsigned NULL DEFAULT 0;");
$db->getConnection()->exec("ALTER TABLE `documents_permissions` CHANGE COLUMN `versions` `versions` tinyint(1) unsigned NULL DEFAULT 0;");
$db->getConnection()->exec("ALTER TABLE `documents_permissions` CHANGE COLUMN `properties` `properties` tinyint(1) unsigned NULL DEFAULT 0;");
$db->getConnection()->exec("ALTER TABLE `documents_permissions` CHANGE COLUMN `view` `view` tinyint(1) unsigned NULL DEFAULT 0;");
$db->getConnection()->exec("ALTER TABLE `documents_snippet` CHANGE COLUMN `id` `id` int(11) unsigned NULL DEFAULT NULL;");
$db->getConnection()->exec("ALTER TABLE `glossary` ADD INDEX `language` (`language`(2));");
$db->getConnection()->exec("ALTER TABLE `glossary` CHANGE COLUMN `id` `id` int(11) unsigned NOT NULL AUTO_INCREMENT;");
$db->getConnection()->exec("ALTER TABLE `objects` ADD INDEX `parentId` (`o_parentId`);");
$db->getConnection()->exec("ALTER TABLE `objects` CHANGE COLUMN `o_id` `o_id` int(11) unsigned NOT NULL AUTO_INCREMENT;");
$db->getConnection()->exec("ALTER TABLE `objects` CHANGE COLUMN `o_parentId` `o_parentId` int(11) unsigned NULL DEFAULT NULL;");
$db->getConnection()->exec("ALTER TABLE `objects` CHANGE COLUMN `o_index` `o_index` int(11) unsigned NULL DEFAULT 0;");
$db->getConnection()->exec("ALTER TABLE `objects` CHANGE COLUMN `o_published` `o_published` tinyint(1) unsigned NULL DEFAULT 1;");
$db->getConnection()->exec("ALTER TABLE `objects` CHANGE COLUMN `o_creationDate` `o_creationDate` bigint(20) unsigned NULL DEFAULT NULL;");
$db->getConnection()->exec("ALTER TABLE `objects` CHANGE COLUMN `o_modificationDate` `o_modificationDate` bigint(20) unsigned NULL DEFAULT NULL;");
$db->getConnection()->exec("ALTER TABLE `objects` CHANGE COLUMN `o_userOwner` `o_userOwner` int(11) unsigned NULL DEFAULT NULL;");
$db->getConnection()->exec("ALTER TABLE `objects` CHANGE COLUMN `o_userModification` `o_userModification` int(11) unsigned NULL DEFAULT NULL;");
$db->getConnection()->exec("ALTER TABLE `objects` CHANGE COLUMN `o_classId` `o_classId` int(11) unsigned NULL DEFAULT NULL;");
$db->getConnection()->exec("ALTER TABLE `objects_data` ADD INDEX `o_id` (`o_id`);");
$db->getConnection()->exec("ALTER TABLE `objects_data` CHANGE COLUMN `serialized` `serialized` tinyint(1) unsigned NULL DEFAULT 0;");
$db->getConnection()->exec("ALTER TABLE `objects_data` CHANGE COLUMN `o_id` `o_id` int(11) unsigned NOT NULL DEFAULT 0;");
$db->getConnection()->exec("ALTER TABLE `objects_permissions` CHANGE COLUMN `id` `id` int(11) unsigned NOT NULL AUTO_INCREMENT;");
$db->getConnection()->exec("ALTER TABLE `objects_permissions` CHANGE COLUMN `cid` `cid` int(11) unsigned NULL DEFAULT NULL;");
$db->getConnection()->exec("ALTER TABLE `objects_permissions` CHANGE COLUMN `userId` `userId` int(11) unsigned NULL DEFAULT NULL;");
$db->getConnection()->exec("ALTER TABLE `objects_permissions` CHANGE COLUMN `list` `list` tinyint(1) unsigned NULL DEFAULT 0;");
$db->getConnection()->exec("ALTER TABLE `objects_permissions` CHANGE COLUMN `view` `view` tinyint(1) unsigned NULL DEFAULT 0;");
$db->getConnection()->exec("ALTER TABLE `objects_permissions` CHANGE COLUMN `save` `save` tinyint(1) unsigned NULL DEFAULT 0;");
$db->getConnection()->exec("ALTER TABLE `objects_permissions` CHANGE COLUMN `publish` `publish` tinyint(1) unsigned NULL DEFAULT 0;");
$db->getConnection()->exec("ALTER TABLE `objects_permissions` CHANGE COLUMN `unpublish` `unpublish` tinyint(1) unsigned NULL DEFAULT 0;");
$db->getConnection()->exec("ALTER TABLE `objects_permissions` CHANGE COLUMN `delete` `delete` tinyint(1) unsigned NULL DEFAULT 0;");
$db->getConnection()->exec("ALTER TABLE `objects_permissions` CHANGE COLUMN `rename` `rename` tinyint(1) unsigned NULL DEFAULT 0;");
$db->getConnection()->exec("ALTER TABLE `objects_permissions` CHANGE COLUMN `create` `create` tinyint(1) unsigned NULL DEFAULT 0;");
$db->getConnection()->exec("ALTER TABLE `objects_permissions` CHANGE COLUMN `permissions` `permissions` tinyint(1) unsigned NULL DEFAULT 0;");
$db->getConnection()->exec("ALTER TABLE `objects_permissions` CHANGE COLUMN `settings` `settings` tinyint(1) unsigned NULL DEFAULT 0;");
$db->getConnection()->exec("ALTER TABLE `objects_permissions` CHANGE COLUMN `versions` `versions` tinyint(1) unsigned NULL DEFAULT 0;");
$db->getConnection()->exec("ALTER TABLE `objects_permissions` CHANGE COLUMN `properties` `properties` tinyint(1) unsigned NULL DEFAULT 0;");
$db->getConnection()->exec("ALTER TABLE `properties` CHANGE COLUMN `inheritable` `inheritable` tinyint(1) unsigned NULL DEFAULT 1;");
$db->getConnection()->exec("ALTER TABLE `properties` CHANGE COLUMN `cid` `cid` int(11) unsigned NULL DEFAULT 0;");
$db->getConnection()->exec("ALTER TABLE `properties_predefined` CHANGE COLUMN `id` `id` int(11) unsigned NOT NULL AUTO_INCREMENT;");
$db->getConnection()->exec("ALTER TABLE `redirects`   CHANGE COLUMN `id` `id` int(11) unsigned NOT NULL AUTO_INCREMENT;");
$db->getConnection()->exec("ALTER TABLE `schedule_tasks` CHANGE COLUMN `id` `id` int(11) unsigned NOT NULL AUTO_INCREMENT;");
$db->getConnection()->exec("ALTER TABLE `schedule_tasks` CHANGE COLUMN `cid` `cid` int(11) unsigned NULL DEFAULT NULL;");
$db->getConnection()->exec("ALTER TABLE `schedule_tasks` CHANGE COLUMN `date` `date` bigint(20) unsigned NULL DEFAULT NULL;");
$db->getConnection()->exec("ALTER TABLE `schedule_tasks` CHANGE COLUMN `active` `active` tinyint(1) unsigned NULL DEFAULT 0;");
$db->getConnection()->exec("ALTER TABLE `schedule_tasks` CHANGE COLUMN `version` `version` bigint(20) unsigned NULL DEFAULT NULL;");
$db->getConnection()->exec("ALTER TABLE `sites` CHANGE COLUMN `id` `id` int(11) unsigned NOT NULL AUTO_INCREMENT;");
$db->getConnection()->exec("ALTER TABLE `sites` CHANGE COLUMN `rootId` `rootId` int(11) unsigned NULL DEFAULT NULL;");
$db->getConnection()->exec("ALTER TABLE `staticroutes` CHANGE COLUMN `id` `id` int(11) unsigned NOT NULL AUTO_INCREMENT;");
$db->getConnection()->exec("ALTER TABLE `staticroutes` ADD INDEX `priority` (`priority`);");
$db->getConnection()->exec("ALTER TABLE `thumbnails` CHANGE COLUMN `id` `id` int(11) unsigned NOT NULL AUTO_INCREMENT;");
$db->getConnection()->exec("ALTER TABLE `thumbnails` CHANGE COLUMN `width` `width` int(11) unsigned NULL DEFAULT NULL;");
$db->getConnection()->exec("ALTER TABLE `thumbnails` CHANGE COLUMN `height` `height` int(11) unsigned NULL DEFAULT NULL;");
$db->getConnection()->exec("ALTER TABLE `thumbnails` CHANGE COLUMN `aspectratio` `aspectratio` tinyint(1) unsigned NULL DEFAULT 0;");
$db->getConnection()->exec("ALTER TABLE `thumbnails` CHANGE COLUMN `interlace` `interlace` tinyint(1) unsigned NULL DEFAULT 0;");
$db->getConnection()->exec("ALTER TABLE `translations` CHANGE COLUMN `date` `date` bigint(20) unsigned NULL DEFAULT NULL;");
$db->getConnection()->exec("ALTER TABLE `users` CHANGE COLUMN `id` `id` int(11) unsigned NOT NULL AUTO_INCREMENT;");
$db->getConnection()->exec("ALTER TABLE `users` CHANGE COLUMN `parentId` `parentId` int(11) unsigned NULL DEFAULT NULL;");
$db->getConnection()->exec("ALTER TABLE `users` ADD INDEX `parentId` (`parentId`);");
$db->getConnection()->exec("ALTER TABLE `users` CHANGE COLUMN `admin` `admin` tinyint(1) unsigned NULL DEFAULT 0;");
$db->getConnection()->exec("ALTER TABLE `users` CHANGE COLUMN `hasCredentials` `hasCredentials` tinyint(1) unsigned NULL DEFAULT 1;");
$db->getConnection()->exec("ALTER TABLE `users_permissions` CHANGE COLUMN `Id` `Id` int(11) unsigned NULL DEFAULT NULL;");
$db->getConnection()->exec("ALTER TABLE `users_permissions` CHANGE COLUMN `userId` `userId` int(11) unsigned NULL DEFAULT NULL;");
$db->getConnection()->exec("ALTER TABLE `versions` CHANGE COLUMN `id` `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT;");
$db->getConnection()->exec("ALTER TABLE `versions` CHANGE COLUMN `cid` `cid` int(11) unsigned NULL DEFAULT NULL;");
$db->getConnection()->exec("ALTER TABLE `versions` CHANGE COLUMN `userId` `userId` int(11) unsigned NULL DEFAULT NULL;");
$db->getConnection()->exec("ALTER TABLE `versions` CHANGE COLUMN `date` `date` bigint(1) unsigned NULL DEFAULT NULL;");
$db->getConnection()->exec("ALTER TABLE `versions` CHANGE COLUMN `serialized` `serialized` tinyint(1) unsigned NULL DEFAULT 0;");

?>