<?php

// constants generated in pimcore/config/constants.php
define('PIMCORE_COMPOSER_PATH', '');
define('PIMCORE_COMPOSER_FILE_PATH', '');
define('PIMCORE_PATH', '');
define('PIMCORE_APP_ROOT', '');
define('PIMCORE_WEB_ROOT', '');
define('PIMCORE_PRIVATE_VAR', '');
define('PIMCORE_PUBLIC_VAR', '');
define('PIMCORE_CLASS_DIRECTORY', '');
define('PIMCORE_ASSET_DIRECTORY', '');
define('PIMCORE_CUSTOM_CONFIGURATION_DIRECTORY', '');
define('PIMCORE_CONFIGURATION_DIRECTORY', '');
define('PIMCORE_VERSION_DIRECTORY', '');
define('PIMCORE_LOG_DIRECTORY', '');
define('PIMCORE_LOG_FILEOBJECT_DIRECTORY', '');
define('PIMCORE_LOG_MAIL_TEMP', '');
define('PIMCORE_TEMPORARY_DIRECTORY', '');
define('PIMCORE_CACHE_DIRECTORY', '');
define('PIMCORE_CUSTOMLAYOUT_DIRECTORY', '');
define('PIMCORE_RECYCLEBIN_DIRECTORY', '');
define('PIMCORE_SYSTEM_TEMP_DIRECTORY', '');
define('PIMCORE_LOG_MAIL_PERMANENT', '');
define('PIMCORE_USERIMAGE_DIRECTORY', '');
define('PIMCORE_PROJECT_ROOT', '');
