<?php

// constants generated in lib/Bootstrap.php
define('PIMCORE_COMPOSER_PATH', '');
define('PIMCORE_COMPOSER_FILE_PATH', '');
define('PIMCORE_PATH', '');
define('PIMCORE_WEB_ROOT', '');
define('PIMCORE_PRIVATE_VAR', '');
define('PIMCORE_CLASS_DIRECTORY', '');
define('PIMCORE_CLASS_DEFINITION_DIRECTORY', '');
define('PIMCORE_CUSTOM_CONFIGURATION_DIRECTORY', '');
define('PIMCORE_CONFIGURATION_DIRECTORY', '');
define('PIMCORE_LOG_DIRECTORY', '');
define('PIMCORE_CACHE_DIRECTORY', '');
define('PIMCORE_LOG_FILEOBJECT_DIRECTORY', '');
define('PIMCORE_CUSTOMLAYOUT_DIRECTORY', '');
define('PIMCORE_SYSTEM_TEMP_DIRECTORY', '');
define('PIMCORE_PROJECT_ROOT', '');
define('PIMCORE_SYMFONY_CACHE_DIRECTORY', '');
define('PIMCORE_PHP_ERROR_LOG', '');
define('PIMCORE_KERNEL_CLASS', '');
define('PIMCORE_APP_BUNDLE_CLASS_FILE', '');
