pimcore_seo:
    redirects:
        status_codes:
            300: Multiple Choices
            301: Moved Permanently
            302: Found
            303: See Other
            307: Temporary Redirect
        auto_create_redirects: false