<?php  //[STAMP] 257ee6196ddd9002a57b3adb629712bf
// phpcs:ignoreFile
namespace Pimcore\Bundle\PersonalizationBundle\Tests\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build

trait UnitTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
