<?php
// made by Twitter user @remisouverain
if ($this->pageCount): ?>
	<ul class="pagination">
	<!-- <li class="desc disabled"><a href="#"><?= $this->firstItemNumber; ?>-<?= $this->lastItemNumber; ?> / <?= $this->totalItemCount; ?></a></li> -->
	
	<?php if (isset($this->previous)): ?>
		<li class="first"><a href="<?= $this->path(['page' => $this->first, "q" => $this->app("request")->get("q")]); ?>"><?= $this->first; ?> &larr;</a></li>
	<?php endif; ?>
	

	
<?php foreach ($this->pagesInRange as $page)
{
	$class = '';
	if ($page == $this->current) $class = 'active';
	if( ($this->first < $page) && ($page < $this->last) || $page == $this->current)
	{
?>
		<li class="<?= $class; ?>"><a href="<?= $this->path(['page' => $page, "q" => $this->app("request")->get("q")]); ?>"><?= $page; ?></a></li>
<?php
	}
}
?>

	<?php if (isset($this->next)): ?>
		<li class="last"><a href="<?= $this->path(['page' => $this->last, "q" => $this->app("request")->get("q")]); ?>">&rarr; <?= $this->last; ?></a></li>
	<?php endif; ?>

	</ul>
<?php endif; ?>
