<?php
    // add autogenerated meta description
    $this->headMeta()->setName('description', Website_Tool_Text::cutStringRespectingWhitespace(Website_Tool_Text::getStringAsOneLine(strip_tags($this->wysiwyg("content")->getData())), 160));
?>

<section class="area-wysiwyg">

    <?php $this->template("/includes/area-headlines.php"); ?>

    <?php $this->glossary()->start(); ?>
        <?= $this->wysiwyg("content"); ?>
    <?php $this->glossary()->stop(); ?>

</section>