<?php
    // add autogenerated meta description
    $this->headMeta()->setName('description', \Website\Tool\Text::cutStringRespectingWhitespace(\Website\Tool\Text::getStringAsOneLine(strip_tags($this->wysiwyg("content")->getData())), 160));
?>

<section class="area-wysiwyg">

    <?php $this->glossary()->start(); ?>
        <?= $this->wysiwyg("content"); ?>
    <?php $this->glossary()->stop(); ?>

</section>