<?php
/**
 * @var \Pimcore\Bundle\PimcoreBundle\Templating\PhpEngine $this
 * @var \Pimcore\Bundle\PimcoreBundle\Templating\PhpEngine $view
 * @var \Pimcore\Bundle\PimcoreBundle\Templating\GlobalVariables\GlobalVariables $app
 */
?>


<?php
    // add autogenerated meta description
    // TODO HEAD META HELPER
    // $this->headMeta()->setName('description', \Website\Tool\Text::cutStringRespectingWhitespace(\Website\Tool\Text::getStringAsOneLine(strip_tags($this->wysiwyg("content")->getData())), 160));
?>

<section class="area-wysiwyg">

    <?php $this->glossary()->start(); ?>
        <?= $this->wysiwyg("content"); ?>
    <?php $this->glossary()->stop(); ?>

</section>
