<?php
declare(strict_types=1);

/**
 * This source file is available under the terms of the
 * Pimcore Open Core License (POCL)
 * Full copyright and license information is available in
 * LICENSE.md which is distributed with this source code.
 *
 *  @copyright  Copyright (c) Pimcore GmbH (https://www.pimcore.com)
 *  @license    Pimcore Open Core License (POCL)
 */

namespace Pimcore\Bundle\CoreBundle\DependencyInjection\Compiler;

use Pimcore\Routing\Loader\AttributeRouteControllerLoader;
use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;
use Symfony\Component\DependencyInjection\ContainerBuilder;

/**
 * Set attribute loader to our own implementation normalizing admin routes: converts the prefix
 * pimcore_pimcoreadmin_ to just pimcore_admin_
 *
 * @internal
 */
final class RoutingLoaderPass implements CompilerPassInterface
{
    /**
     * Replace Attribute Routing loader with your implementation to normalizes autogenerated admin routes
     */
    public function process(ContainerBuilder $container): void
    {
        if (!$container->hasDefinition('routing.loader.attribute')) {
            return;
        }

        $definition = $container->getDefinition('routing.loader.attribute');
        $definition->setClass(AttributeRouteControllerLoader::class);
    }
}
