name: "PHP-CS-Fixer"

on:
    push:
        branches:
            - "[0-9]+.[0-9]+"
            - "[0-9]+.x"

permissions:
    contents: write

jobs:
    php-style:
        uses: pimcore/workflows-collection-public/.github/workflows/reusable-php-cs-fixer.yaml@main
        if: github.repository_owner == 'pimcore'
        secrets:
            PHP_CS_FIXER_GITHUB_TOKEN: ${{ secrets.PHP_CS_FIXER_GITHUB_TOKEN }}
        with:
            head_ref: ${{ github.head_ref || github.ref_name }}
            repository: ${{ github.repository }}
            config_file: .php-cs-fixer.dist.php
