
name: "Psalm Static Analysis"

on:
    pull_request:
        branches:
            - "[0-9]+.[0-9]+"
            - "[0-9]+.x"
    push:
        branches:
            - "[0-9]+.[0-9]+"
            - "[0-9]+.x"
            - "*_actions"

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    psalm:
        name: Psalm
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Psalm
              uses: docker://ghcr.io/psalm/psalm-github-actions
              with:
                security_analysis: true
                composer_ignore_platform_reqs: true
